### PR TITLE
Adding `DatePicker`

### LINKED ISSUE #169: TimeField and DateField that return a `Dates.Time` and `Dates.Date`
We already have a `TimeField` widget that returns the selected time as a *String* (boooo), which was the only possibility last year.

Since #148 , it is possible to **transform** a value before assigning it to the bound julia variable. For example, take a look at https://github.com/JuliaPluto/PlutoUI.jl/pull/168

This means that we can create a new `TimeField` and `DateField` that return the Julia date and time fields directly!

Let's call it `TimePicker` and `DatePicker` to avoid breaking the existing functions.

### PR DESCRIPTION
**Pull request by icweaver**
Follow-up from #179

Closes #169 after #181 merged

### CODE REVIEW

**Comment by fonsp** [comment]
It looks like Pluto already converts to a Julia `DateTime` (nice!), can you convert it to a `Date`, dropping the time?

**Comment by icweaver** [comment]
Ok, things should be up now! It looks like date validation is already automatic (sweet), but do we want to add extra features like [min/max dates](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date#setting_maximum_and_minimum_dates) as well?

**Comment by fonsp** [comment]
Awesome!!!!

**Pull request merged**
