### PR TITLE
Use an external JS library for consistent smooth scrolling

### LINKED ISSUE #238: Problems with scrolling header into view after TableOfContents click
I am facing issues with navigating through long documents by clicking on the headers of the new TableOfContents.

The issue is present for me when using edge/chromium on windows as browser and connecting to a Pluto server with windows/linux (I tested both locally on windows and still with the browser on Windows but connecting to a remote linux server hosting Pluto).
Edit: I tested on firefox and the problem doesn't appear there, I also tested specific calls to `element.scrollIntoView` and it seems that smooth scrolling has issues in chromium even outside of the TableOfContents

The problem is that when opening a page and trying to click onto a header in the TableOfContents, the scrolling into view seems to interrupt before reaching the element. For elements quite far in the document, I need to click multiple times before finally reaching the element.

Strangely enough, once an element has been reached, scrolling back into it after going back to the top of the document seems to work fine.
If I refresh the page though, the problem presents itself again.

I tested this behavior with the notebook defining the TableOfContents below:

https://user-images.githubusercontent.com/12846528/202744555-74525efe-b818-405c-ba49-daebc314c93c.mp4

### PR DESCRIPTION
**Pull request by disberd**
As discussed in #238, the smooth scrolling is broken in some browsers (e.g. Chrome).

This PR just loads an external library to ensure consistent smooth scrolling across browsers.

The library seems maintained and seems to solve the problem in the issue, so it fixes #238.

Here is a video example like in #238 

https://user-images.githubusercontent.com/12846528/235166253-562a9b65-f1ce-4013-9843-aa2eeec75efe.mp4

### CODE REVIEW

**Comment by disberd** [comment]
This might create issues when opening Pluto notebooks while offline as the library for smooth scrolling can't be downloaded.
What is the best approach here?
Since this is to some extent a problem also in jumps in Pluto we might have this used internally in Pluto and be provided as asset....

**Comment by fonsp** [comment]
Awesome! Like you pointed out, using an external library is not ideal. I went for the easiest solution: just bundle it by hand and inline into our code.

I also added a second call to `scrollIntoView` to fix some wrong scrolls when you initially loaded a notebook. The first time you scroll somewhere, the codemirrors will get rendered and their heights may change.


https://user-images.githubusercontent.com/6933510/235625618-62ab0626-7cc1-4d5c-a253-03b06895e6a4.mov

**Comment by fonsp** [comment]
Thanks!!

**Comment by fonsp** [comment]
Releasing in v0.7.51

**Pull request merged**
