### PR TITLE
Add `combine`

### PR DESCRIPTION
**Pull request by fonsp**
https://htmlview.glitch.me/?https://gist.github.com/fonsp/056877529633cdbc4e91fcabdb056d3f#file-combine-jl-html

Schermopname 2021-12-10 om 18 21 56

### CODE REVIEW

**Comment by Pangoraw** [comment]
Very cool! What do you think about transforming into a tuple instead of a vector and also making a named tuple variant ?

**Comment by fonsp** [comment]
Awesome idea @Pangoraw !

**Comment by fonsp** [comment]
@disberd

**Comment by disberd** [comment]
Cool!

**Pull request merged**
