### PR TITLE
Dark background for TOC

### PR DESCRIPTION
**Pull request by pankgeorg**

### CODE REVIEW

**Comment by icweaver** [comment]
This is awesome, thanks for working on this Panagiotis! Not sure if this is the right place, but I was wondering if the "Edit or run this notebook" button could also get a little TLC?

Screenshot from 2022-01-22 11-15-51

I'd be happy to start a PR for this to get the ball rolling if it doesn't require too much Pluto magic 🪄

**Comment by fonsp** [comment]
hmmmmmm but this is using Pluto's internal CSS variables! Weren't you the one who told me that widget authors surely won't use those and create their own CSS variables?

**Comment by fonsp** [comment]
@icweaver well spotted! That button is part of Pluto itself, but it is a bit difficult to work on because ~you can only see it on the export output, which uses Pluto's CSS from the last release... You either have to set up a local file server to replace the pluto CDN while developing (or you just~ okay I decided to just quickly fix this instead :) https://github.com/fonsp/Pluto.jl/commit/111960219770272ff8c1a700f1f894bf50348db9

**Comment by pankgeorg** [comment]
> hmmmmmm but this is using Pluto's internal CSS variables!
yes!

> Weren't you the one who told me that widget authors surely won't use those and create their own CSS variables?

I said that widget authors can _override_ those while using them on their own styles! Take a look at [this](https://github.com/JuliaPluto/PlutoUI.jl/pull/193/commits/067ba5ee1b6d135e23ee2a1968a40da3139f90c6), where I do exactly that :)

**Comment by icweaver** [comment]
Was hoping to bump this. It looks so good!

**Comment by icweaver** [comment]
thank-you

**Pull request merged**
